create extension if not exists pgcrypto;

create table if not exists public.app_users (
  id uuid primary key default gen_random_uuid(),
  google_sub text not null unique,
  email text not null unique,
  display_name text,
  image_url text,
  is_admin boolean not null default false,
  next_place_at timestamptz,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.placements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.app_users(id) on delete cascade,
  x integer not null check (x >= 0 and x < 1891),
  y integer not null check (y >= 0 and y < 1891),
  color integer not null check (color >= 0 and color < 32),
  placed_at timestamptz not null default now(),
  ip_hash text,
  user_agent_hash text
);

create index if not exists placements_user_id_placed_at_idx
  on public.placements(user_id, placed_at desc);

create index if not exists placements_xy_placed_at_idx
  on public.placements(x, y, placed_at desc);

create table if not exists public.current_pixels (
  x integer not null check (x >= 0 and x < 1891),
  y integer not null check (y >= 0 and y < 1891),
  color integer not null check (color >= 0 and color < 32),
  updated_at timestamptz not null default now(),
  updated_by uuid not null references public.app_users(id) on delete restrict,
  primary key (x, y)
);

create index if not exists current_pixels_updated_at_idx
  on public.current_pixels(updated_at desc);

create table if not exists public.suspensions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.app_users(id) on delete cascade,
  reason text not null,
  starts_at timestamptz not null default now(),
  expires_at timestamptz,
  revoked_at timestamptz,
  created_by uuid references public.app_users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists suspensions_user_state_idx
  on public.suspensions(user_id, revoked_at, expires_at);

create table if not exists public.app_settings (
  id boolean primary key default true check (id),
  read_only boolean not null default false,
  updated_at timestamptz not null default now()
);

insert into public.app_settings (id, read_only)
values (true, false)
on conflict (id) do nothing;

alter table public.app_users enable row level security;
alter table public.placements enable row level security;
alter table public.current_pixels enable row level security;
alter table public.suspensions enable row level security;
alter table public.app_settings enable row level security;

drop policy if exists "app_users_self_select" on public.app_users;
create policy "app_users_self_select"
  on public.app_users
  for select
  to authenticated
  using ((select auth.uid()) = id);

drop policy if exists "current_pixels_authenticated_select" on public.current_pixels;
create policy "current_pixels_authenticated_select"
  on public.current_pixels
  for select
  to authenticated
  using (true);

drop policy if exists "placements_authenticated_select" on public.placements;
create policy "placements_authenticated_select"
  on public.placements
  for select
  to authenticated
  using (true);

create or replace function public.place_pixel(
  p_user_id uuid,
  p_x integer,
  p_y integer,
  p_color integer,
  p_ip_hash text default null,
  p_user_agent_hash text default null
)
returns table (
  x integer,
  y integer,
  color integer,
  user_id uuid,
  updated_at timestamptz,
  next_place_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  locked_user public.app_users%rowtype;
  current_setting public.app_settings%rowtype;
  active_suspension public.suspensions%rowtype;
  placed_at_value timestamptz := now();
  next_place_value timestamptz := placed_at_value + interval '1 minute';
begin
  if auth.uid() is distinct from p_user_id then
    raise exception 'authenticated user does not match placement user';
  end if;

  select *
    into current_setting
    from public.app_settings
   where id = true;

  if coalesce(current_setting.read_only, false) then
    raise exception 'board is read-only';
  end if;

  select *
    into locked_user
    from public.app_users
   where id = p_user_id
   for update;

  if not found then
    raise exception 'user not found';
  end if;

  if locked_user.next_place_at is not null and locked_user.next_place_at > placed_at_value then
    raise exception 'cooldown active';
  end if;

  select *
    into active_suspension
    from public.suspensions as s
   where s.user_id = p_user_id
     and s.revoked_at is null
     and s.starts_at <= placed_at_value
     and (s.expires_at is null or s.expires_at > placed_at_value)
   order by s.starts_at desc
   limit 1;

  if found then
    raise exception 'user suspended';
  end if;

  insert into public.placements (
    user_id,
    x,
    y,
    color,
    placed_at,
    ip_hash,
    user_agent_hash
  )
  values (
    p_user_id,
    p_x,
    p_y,
    p_color,
    placed_at_value,
    p_ip_hash,
    p_user_agent_hash
  );

  insert into public.current_pixels (
    x,
    y,
    color,
    updated_at,
    updated_by
  )
  values (
    p_x,
    p_y,
    p_color,
    placed_at_value,
    p_user_id
  )
  on conflict on constraint current_pixels_pkey do update
    set color = excluded.color,
        updated_at = excluded.updated_at,
        updated_by = excluded.updated_by;

  update public.app_users
     set next_place_at = next_place_value,
         last_seen_at = placed_at_value
   where id = p_user_id;

  return query
  select
    p_x,
    p_y,
    p_color,
    p_user_id,
    placed_at_value,
    next_place_value;
end;
$$;

revoke all on function public.place_pixel(uuid, integer, integer, integer, text, text) from public;
grant execute on function public.place_pixel(uuid, integer, integer, integer, text, text) to authenticated;

alter publication supabase_realtime add table public.current_pixels;
alter publication supabase_realtime add table public.placements;
